- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4832/workspace/MvnAnsible/target/MvnAnsibleWebapp-1.0-SNAPSHOT.war"
        dest: "/opt/tomcat/webapps/MvnAnsibleWebapp-1.0-SNAPSHOT.war"
        remote_src: no
    - name:  Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
